import {
  PanelTop,
  Server,
  Cog,
  RefreshCw,
  Gauge,
  Wrench,
  Droplets,
  Waves,
  Thermometer,
  Flame,
  Filter,
  Recycle,
  CupSoda,
  Sun,
  TriangleAlert,
  Bolt,
  FlaskConical,
  SprayCan,
  RadioTower,
  Target,
  FileText,
  Check,
  X,
  Mail,
  ClipboardList,
  ImageOff,
  Wifi,
  ShieldAlert,
  Phone,
  Plus,
  Trash2,
  Pencil,
  Upload,
  ShoppingCart,
  LogIn,
  Tag,
  Package,
  Users,
  Settings,
  LayoutDashboard,
  ChevronRight,
  ChevronDown,
  Save,
  Menu,
  SlidersHorizontal,
  Armchair,
  CircleDot,
  Waypoints,
  Handshake,
  ExternalLink,
  MapPin,
  Building2,
  ArrowRight,
  type LucideIcon,
} from "lucide-react";

// Central icon registry — referenced by string name from data (categories,
// use-cases) and components, so no emoji are used anywhere in the UI.
const ICONS: Record<string, LucideIcon> = {
  // Categories
  "panel-top": PanelTop,
  server: Server,
  cog: Cog,
  "refresh-cw": RefreshCw,
  gauge: Gauge,
  wrench: Wrench,
  // Use cases
  droplets: Droplets,
  waves: Waves,
  thermometer: Thermometer,
  flame: Flame,
  filter: Filter,
  recycle: Recycle,
  "cup-soda": CupSoda,
  sun: Sun,
  "triangle-alert": TriangleAlert,
  bolt: Bolt,
  "flask-conical": FlaskConical,
  "spray-can": SprayCan,
  "radio-tower": RadioTower,
  // UI accents
  target: Target,
  "file-text": FileText,
  check: Check,
  x: X,
  mail: Mail,
  "clipboard-list": ClipboardList,
  "image-off": ImageOff,
  wifi: Wifi,
  "shield-alert": ShieldAlert,
  phone: Phone,
  plus: Plus,
  "trash-2": Trash2,
  pencil: Pencil,
  upload: Upload,
  "shopping-cart": ShoppingCart,
  "log-in": LogIn,
  tag: Tag,
  package: Package,
  users: Users,
  settings: Settings,
  "layout-dashboard": LayoutDashboard,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  save: Save,
  menu: Menu,
  "sliders-horizontal": SlidersHorizontal,
  armchair: Armchair,
  "circle-dot": CircleDot,
  waypoints: Waypoints,
  handshake: Handshake,
  "external-link": ExternalLink,
  "map-pin": MapPin,
  "building-2": Building2,
  "arrow-right": ArrowRight,
};

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  className,
  size,
  strokeWidth,
}: {
  name: string;
  className?: string;
  size?: number;
  strokeWidth?: number;
}) {
  const Cmp = ICONS[name] ?? ICONS["panel-top"];
  return <Cmp className={className} size={size} strokeWidth={strokeWidth} aria-hidden />;
}
